import { Film, Genre, Review, FilmList } from '../types';

export const mockGenres: Genre[] = [
  { id: 'g1', name: 'Action' },
  { id: 'g2', name: 'Drama' },
  { id: 'g3', name: 'Comedy' },
  { id: 'g4', name: 'Sci-Fi' },
  { id: 'g5', name: 'Horror' },
  { id: 'g6', name: 'Romance' },
  { id: 'g7', name: 'Thriller' },
];

export const mockFilms: Film[] = [
  { 
    id: 'f1', 
    title: 'The Matrix', 
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 
    release_date: '1999-03-31', 
    poster_url: 'http://www.blackxperience.com/assets/content/blackattitude/blackstyle/poster-film-the-matrix-1999.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=vKQi3bBA1y8', 
    genre_id: 'g4', 
    genre: mockGenres[3], 
    rating: 8.7,
    director: 'Lana Wachowski, Lilly Wachowski',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    duration: 136,
    language: 'English',
    format: ['4K', 'IMAX', 'Dolby Atmos']
  },
  { 
    id: 'f2', 
    title: 'Inception', 
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 
    release_date: '2010-07-16', 
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTM0MjUzNjkwMl5BMl5BanBnXkFtZTcwNjY0OTk1Mw@@._V1_.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=YoHD9XEInc0', 
    genre_id: 'g4', 
    genre: mockGenres[3], 
    rating: 8.8,
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    duration: 148,
    language: 'English',
    format: ['4K', 'IMAX', 'HDR']
  },
  { 
    id: 'f3', 
    title: 'The Dark Knight', 
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham.', 
    release_date: '2008-07-18', 
    poster_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTurBdees5TA8xJaSTUzLblttbpJ4S-juZjcbkuWH8_qlJzLN0XRsPcPfxu0fMUukPRAaIXrJd2tCplJba6xTEWhngOjlASw6Ql2PJA061F3Q&s=10', 
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY', 
    genre_id: 'g1', 
    genre: mockGenres[0], 
    rating: 9.0,
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
    duration: 152,
    language: 'English',
    format: ['4K', 'IMAX']
  },
  { 
    id: 'f4', 
    title: 'Pulp Fiction', 
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 
    release_date: '1994-10-14', 
    poster_url: 'https://play-lh.googleusercontent.com/R17n61if6c2Wc7TLcR43Fe7BV3n8JA1kJG8Gmvaa0-wK-rfoVn9jdP-apKeeHnsUNqDz=w240-h480-rw', 
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY', 
    genre_id: 'g2', 
    genre: mockGenres[1], 
    rating: 8.9,
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
    duration: 154,
    language: 'English',
    format: ['4K', 'Dolby Digital']
  },
  { 
    id: 'f5', 
    title: 'Forrest Gump', 
    description: 'The history of the United States from the 1950s to the \'70s unfolds from the perspective of an Alabama man with an IQ of 75.', 
    release_date: '1994-07-06', 
    poster_url: 'https://m.media-amazon.com/images/S/pv-target-images/22b7552b329aa7d1718ef2be6f046637d3dfebc9e1f972c38b90abc1fb1ef489.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg', 
    genre_id: 'g2', 
    genre: mockGenres[1], 
    rating: 8.8,
    director: 'Robert Zemeckis',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Sally Field'],
    duration: 142,
    language: 'English',
    format: ['4K', 'HDR10']
  },
  { 
    id: 'f6', 
    title: 'The Shawshank Redemption', 
    description: 'Two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.', 
    release_date: '1994-09-23', 
    poster_url: 'https://upload.wikimedia.org/wikipedia/id/8/81/ShawshankRedemptionMoviePoster.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=6hB3S9bIaco', 
    genre_id: 'g2', 
    genre: mockGenres[1], 
    rating: 9.3,
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler'],
    duration: 142,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f7', 
    title: 'The Godfather', 
    description: 'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant youngest son.', 
    release_date: '1972-03-24', 
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA', 
    genre_id: 'g2', 
    genre: mockGenres[1], 
    rating: 9.2,
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Diane Keaton'],
    duration: 175,
    language: 'English',
    format: ['4K', 'Dolby Vision']
  },
  { 
    id: 'f8', 
    title: 'Interstellar', 
    description: 'A team of researchers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', 
    release_date: '2014-11-07', 
    poster_url: 'https://lsf.go.id/storage/app/resources/resize/300_450_0_0_crop/img_913d6d596f88a0ff14c5d652a6ab93e8.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=zSWdZVtXT7E', 
    genre_id: 'g4', 
    genre: mockGenres[3], 
    rating: 8.6,
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    duration: 169,
    language: 'English',
    format: ['4K', 'IMAX', 'HDR']
  },
  { 
    id: 'f9', 
    title: 'Gladiator', 
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.', 
    release_date: '2000-05-05', 
    poster_url: 'https://awsimages.detik.net.id/community/media/visual/2024/11/12/poster-film-gladiator-2_34.jpeg?w=650&q=90', 
    trailer_url: 'https://www.youtube.com/watch?v=owK1qxDselE', 
    genre_id: 'g1', 
    genre: mockGenres[0], 
    rating: 8.5,
    director: 'Ridley Scott',
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 'Oliver Reed'],
    duration: 155,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f10', 
    title: 'Avengers: Endgame', 
    description: 'The Avengers assemble once more in order to restore balance to the universe.', 
    release_date: '2019-04-26', 
    poster_url: 'https://asset.kompas.com/crops/DjmyQWcXltOoA--p664iWhFHkjU=/182x94:1834x1195/1200x800/data/photo/2019/03/18/2127080686.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=TcMBFSGVi1c', 
    genre_id: 'g1', 
    genre: mockGenres[0], 
    rating: 8.4,
    director: 'Anthony Russo, Joe Russo',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth'],
    duration: 181,
    language: 'English',
    format: ['4K', 'IMAX', 'Dolby Atmos']
  },
  { 
    id: 'f11', 
    title: 'Superbad', 
    description: 'Two co-dependent high school seniors are forced to deal with separation anxiety.', 
    release_date: '2007-08-17', 
    poster_url: 'https://m.media-amazon.com/images/S/pv-target-images/c06b0c0fbaecbcc007702f52f821f96e92ee560b39291fad8b38ea6b9e14031e.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=4eaZ_48ZYIQ', 
    genre_id: 'g3', 
    genre: mockGenres[2], 
    rating: 7.6,
    director: 'Greg Mottola',
    cast: ['Jonah Hill', 'Michael Cera', 'Christopher Mintz-Plasse', 'Bill Hader'],
    duration: 113,
    language: 'English',
    format: ['HD', 'Stereo']
  },
  { 
    id: 'f12', 
    title: 'The Hangover', 
    description: 'Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night.', 
    release_date: '2009-06-05', 
    poster_url: 'https://m.media-amazon.com/images/S/pv-target-images/e0edd8bdd9c9f19fc804e332a39e83be6ba70e9c5cbdf86646000da66a2b2f35.jpg', 
    trailer_url: 'https://www.youtube.com/watch?v=tcdUhdOlz9M', 
    genre_id: 'g3', 
    genre: mockGenres[2], 
    rating: 7.7,
    director: 'Todd Phillips',
    cast: ['Bradley Cooper', 'Ed Helms', 'Zach Galifianakis', 'Justin Bartha'],
    duration: 100,
    language: 'English',
    format: ['HD', 'Dolby Digital']
  },
  { 
    id: 'f13', 
    title: 'Step Brothers', 
    description: 'Two aimless middle-aged losers are forced to become roommates when their parents marry.', 
    release_date: '2008-07-25', 
    poster_url: 'https://picsum.photos/seed/stepbrothers/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=CewglxElBK0', 
    genre_id: 'g3', 
    genre: mockGenres[2], 
    rating: 6.9,
    director: 'Adam McKay',
    cast: ['Will Ferrell', 'John C. Reilly', 'Mary Steenburgen', 'Richard Jenkins'],
    duration: 98,
    language: 'English',
    format: ['HD', 'Stereo']
  },
  { 
    id: 'f14', 
    title: 'Dumb and Dumber', 
    description: 'Two dumb friends set out on a hilarious cross-country road trip to Aspen.', 
    release_date: '1994-12-16', 
    poster_url: 'https://picsum.photos/seed/dumb/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=l13yPhimE3o', 
    genre_id: 'g3', 
    genre: mockGenres[2], 
    rating: 7.3,
    director: 'Peter Farrelly, Bobby Farrelly',
    cast: ['Jim Carrey', 'Jeff Daniels', 'Lauren Holly', 'Teri Garr'],
    duration: 107,
    language: 'English',
    format: ['HD', 'Stereo']
  },
  { 
    id: 'f15', 
    title: 'The Conjuring', 
    description: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence.', 
    release_date: '2013-07-19', 
    poster_url: 'https://picsum.photos/seed/conjuring/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=k10ETZ41q5o', 
    genre_id: 'g5', 
    genre: mockGenres[4], 
    rating: 7.5,
    director: 'James Wan',
    cast: ['Vera Farmiga', 'Patrick Wilson', 'Lili Taylor', 'Ron Livingston'],
    duration: 112,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f16', 
    title: 'Get Out', 
    description: 'A young African-American visits his white girlfriend\'s parents for the weekend with disturbing results.', 
    release_date: '2017-02-24', 
    poster_url: 'https://picsum.photos/seed/getout/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=DzfpyUB60YY', 
    genre_id: 'g5', 
    genre: mockGenres[4], 
    rating: 7.8,
    director: 'Jordan Peele',
    cast: ['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford', 'Catherine Keener'],
    duration: 104,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f17', 
    title: 'A Quiet Place', 
    description: 'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters.', 
    release_date: '2018-04-06', 
    poster_url: 'https://picsum.photos/seed/quietplace/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=WR7cc5t7tv8', 
    genre_id: 'g5', 
    genre: mockGenres[4], 
    rating: 7.5,
    director: 'John Krasinski',
    cast: ['Emily Blunt', 'John Krasinski', 'Millicent Simmonds', 'Noah Jupe'],
    duration: 90,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f18', 
    title: 'Hereditary', 
    description: 'A grieving family is haunted by tragic occurrences after the death of their secretive grandmother.', 
    release_date: '2018-06-08', 
    poster_url: 'https://picsum.photos/seed/hereditary/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=V6wWKNij_1M', 
    genre_id: 'g5', 
    genre: mockGenres[4], 
    rating: 7.3,
    director: 'Ari Aster',
    cast: ['Toni Collette', 'Milly Shapiro', 'Alex Wolff', 'Gabriel Byrne'],
    duration: 127,
    language: 'English',
    format: ['4K', 'HDR']
  },
  { 
    id: 'f19', 
    title: 'The Notebook', 
    description: 'A poor yet passionate young man falls in love with a rich young woman.', 
    release_date: '2004-06-25', 
    poster_url: 'https://picsum.photos/seed/notebook/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=FC6biTjEyZw', 
    genre_id: 'g6', 
    genre: mockGenres[5], 
    rating: 7.8,
    director: 'Nick Cassavetes',
    cast: ['Ryan Gosling', 'Rachel McAdams', 'James Garner', 'Gena Rowlands'],
    duration: 123,
    language: 'English',
    format: ['HD', 'Stereo']
  },
  { 
    id: 'f20', 
    title: 'Titanic', 
    description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the R.M.S. Titanic.', 
    release_date: '1997-12-19', 
    poster_url: 'https://picsum.photos/seed/titanic/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=kVrqfYjkTdQ', 
    genre_id: 'g6', 
    genre: mockGenres[5], 
    rating: 7.9,
    director: 'James Cameron',
    cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane', 'Kathy Bates'],
    duration: 194,
    language: 'English',
    format: ['4K', 'Dolby Vision']
  },
  { 
    id: 'f21', 
    title: 'La La Land', 
    description: 'A pianist and an actress fall in love while attempting to reconcile their aspirations for the future.', 
    release_date: '2016-12-09', 
    poster_url: 'https://picsum.photos/seed/lalaland/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=0pdqf4P9MB8', 
    genre_id: 'g6', 
    genre: mockGenres[5], 
    rating: 8.0,
    director: 'Damien Chazelle',
    cast: ['Ryan Gosling', 'Emma Stone', 'Rosemarie DeWitt', 'J.K. Simmons'],
    duration: 128,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f22', 
    title: 'Pride & Prejudice', 
    description: 'Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy.', 
    release_date: '2005-11-23', 
    poster_url: 'https://picsum.photos/seed/pride/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=1dYv5u6v55Y', 
    genre_id: 'g6', 
    genre: mockGenres[5], 
    rating: 7.8,
    director: 'Joe Wright',
    cast: ['Keira Knightley', 'Matthew Macfadyen', 'Brenda Blethyn', 'Donald Sutherland'],
    duration: 129,
    language: 'English',
    format: ['HD', 'Stereo']
  },
  { 
    id: 'f23', 
    title: 'Se7en', 
    description: 'Two detectives hunt a serial killer who uses the seven deadly sins as his motives.', 
    release_date: '1995-09-22', 
    poster_url: 'https://picsum.photos/seed/seven/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI', 
    genre_id: 'g7', 
    genre: mockGenres[6], 
    rating: 8.6,
    director: 'David Fincher',
    cast: ['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey', 'Gwyneth Paltrow'],
    duration: 127,
    language: 'English',
    format: ['4K', 'Dolby Digital']
  },
  { 
    id: 'f24', 
    title: 'The Silence of the Lambs', 
    description: 'A young F.B.I. cadet must receive the help of an incarcerated cannibal killer to catch another serial killer.', 
    release_date: '1991-02-14', 
    poster_url: 'https://picsum.photos/seed/silence/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=W6Mm8Sbe__o', 
    genre_id: 'g7', 
    genre: mockGenres[6], 
    rating: 8.6,
    director: 'Jonathan Demme',
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn', 'Ted Levine'],
    duration: 118,
    language: 'English',
    format: ['4K', 'Dolby Digital']
  },
  { 
    id: 'f25', 
    title: 'Prisoners', 
    description: 'When a man\'s daughter goes missing, he takes matters into his own hands.', 
    release_date: '2013-09-20', 
    poster_url: 'https://picsum.photos/seed/prisoners/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=bpXfcTF6iVk', 
    genre_id: 'g7', 
    genre: mockGenres[6], 
    rating: 8.1,
    director: 'Denis Villeneuve',
    cast: ['Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis', 'Maria Bello'],
    duration: 153,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f26', 
    title: 'Shutter Island', 
    description: 'A U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital.', 
    release_date: '2010-02-19', 
    poster_url: 'https://picsum.photos/seed/shutter/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=5iaYLCiq5RM', 
    genre_id: 'g7', 
    genre: mockGenres[6], 
    rating: 8.2,
    director: 'Martin Scorsese',
    cast: ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley', 'Max von Sydow'],
    duration: 138,
    language: 'English',
    format: ['4K', 'Dolby Digital']
  },
  { 
    id: 'f27', 
    title: 'Mad Max: Fury Road', 
    description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners and a drifter named Max.', 
    release_date: '2015-05-15', 
    poster_url: 'https://picsum.photos/seed/madmax/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=hEJnMQG9ev8', 
    genre_id: 'g1', 
    genre: mockGenres[0], 
    rating: 8.1,
    director: 'George Miller',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult', 'Hugh Keays-Byrne'],
    duration: 120,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f28', 
    title: 'John Wick', 
    description: 'An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.', 
    release_date: '2014-10-24', 
    poster_url: 'https://picsum.photos/seed/johnwick/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=c0m65W_4h8I', 
    genre_id: 'g1', 
    genre: mockGenres[0], 
    rating: 7.4,
    director: 'Chad Stahelski',
    cast: ['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen', 'Willem Dafoe'],
    duration: 101,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f29', 
    title: 'Parasite', 
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 
    release_date: '2019-05-30', 
    poster_url: 'https://picsum.photos/seed/parasite/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=5xH0HfJHsaY', 
    genre_id: 'g2', 
    genre: mockGenres[1], 
    rating: 8.5,
    director: 'Bong Joon Ho',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'],
    duration: 132,
    language: 'Korean',
    format: ['4K', 'Dolby Digital']
  },
  { 
    id: 'f30', 
    title: 'Dune', 
    description: 'A noble family becomes embroiled in a war for control over the galaxy\'s most valuable asset while its heir becomes troubled by visions of a dark future.', 
    release_date: '2021-10-22', 
    poster_url: 'https://picsum.photos/seed/dune/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=n9xhJrPXop4', 
    genre_id: 'g4', 
    genre: mockGenres[3], 
    rating: 8.0,
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Zendaya', 'Oscar Isaac'],
    duration: 155,
    language: 'English',
    format: ['4K', 'IMAX', 'Dolby Atmos']
  },
  { 
    id: 'f31', 
    title: 'Midsommar', 
    description: 'A couple travels to Scandinavia to visit a rural hometown\'s fabled Swedish midsummer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.', 
    release_date: '2019-07-03', 
    poster_url: 'https://picsum.photos/seed/midsommar/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=1Vnghdsjmd0', 
    genre_id: 'g5', 
    genre: mockGenres[4], 
    rating: 7.1,
    director: 'Ari Aster',
    cast: ['Florence Pugh', 'Jack Reynor', 'Vilhelm Blomgren', 'William Jackson Harper'],
    duration: 148,
    language: 'English',
    format: ['4K', 'HDR']
  },
  { 
    id: 'f32', 
    title: 'About Time', 
    description: 'At the age of 21, Tim discovers he can travel in time and change what happens and has happened in his own life. His decision to make his world a better place by getting a girlfriend turns out not to be as easy as you might think.', 
    release_date: '2013-09-04', 
    poster_url: 'https://picsum.photos/seed/abouttime/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=7OIFdW5jnZo', 
    genre_id: 'g6', 
    genre: mockGenres[5], 
    rating: 7.8,
    director: 'Richard Curtis',
    cast: ['Domhnall Gleeson', 'Rachel McAdams', 'Bill Nighy', 'Margot Robbie'],
    duration: 123,
    language: 'English',
    format: ['HD', 'Stereo']
  },
  { 
    id: 'f33', 
    title: 'Top Gun: Maverick', 
    description: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.', 
    release_date: '2022-05-27', 
    poster_url: 'https://picsum.photos/seed/topgun/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=giXco2jaZ_4', 
    genre_id: 'g1', 
    genre: mockGenres[0], 
    rating: 8.3,
    director: 'Joseph Kosinski',
    cast: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm'],
    duration: 130,
    language: 'English',
    format: ['4K', 'IMAX', 'Dolby Atmos']
  },
  { 
    id: 'f34', 
    title: '12 Angry Men', 
    description: 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.', 
    release_date: '1957-04-10', 
    poster_url: 'https://picsum.photos/seed/12angrymen/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=A7CBKT0PWFA', 
    genre_id: 'g2', 
    genre: mockGenres[1], 
    rating: 9.0,
    director: 'Sidney Lumet',
    cast: ['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam', 'Jack Warden'],
    duration: 96,
    language: 'English',
    format: ['HD', 'Mono']
  },
  { 
    id: 'f35', 
    title: 'Blade Runner 2049', 
    description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him on a quest to find former Blade Runner Rick Deckard, who\'s been missing for thirty years.', 
    release_date: '2017-10-06', 
    poster_url: 'https://picsum.photos/seed/bladerunner/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=gCcx85zbxz4', 
    genre_id: 'g4', 
    genre: mockGenres[3], 
    rating: 8.0,
    director: 'Denis Villeneuve',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Sylvia Hoeks'],
    duration: 164,
    language: 'English',
    format: ['4K', 'IMAX', 'Dolby Atmos']
  },
  { 
    id: 'f36', 
    title: 'Talk to Me', 
    description: 'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.', 
    release_date: '2023-07-28', 
    poster_url: 'https://picsum.photos/seed/talktome/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=aLAKJu9aUXg', 
    genre_id: 'g5', 
    genre: mockGenres[4], 
    rating: 7.1,
    director: 'Danny Philippou, Michael Philippou',
    cast: ['Sophie Wilde', 'Joe Bird', 'Alexandra Jensen', 'Otis Dhanji'],
    duration: 95,
    language: 'English',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f37', 
    title: 'Past Lives', 
    description: 'Nora and Hae Sung, two deeply connected childhood friends, are wrest apart after Nora\'s family emigrates from South Korea. Twenty years later, they are reunited for one fateful week as they confront notions of love and destiny.', 
    release_date: '2023-06-02', 
    poster_url: 'https://picsum.photos/seed/pastlives/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=kA244xewMOh', 
    genre_id: 'g6', 
    genre: mockGenres[5], 
    rating: 7.9,
    director: 'Celine Song',
    cast: ['Greta Lee', 'Teo Yoo', 'John Magaro'],
    duration: 105,
    language: 'English, Korean',
    format: ['4K', 'Dolby Digital']
  },
  { 
    id: 'f38', 
    title: 'Everything Everywhere All At Once', 
    description: 'A middle-aged Chinese immigrant is swept up into an insane adventure, where she alone can save existence by exploring other universes and connecting with the lives she could have led.', 
    release_date: '2022-03-25', 
    poster_url: 'https://picsum.photos/seed/eeaaow/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=wxN1T1uxQ2g', 
    genre_id: 'g4', 
    genre: mockGenres[3], 
    rating: 7.8,
    director: 'Daniel Kwan, Daniel Scheinert',
    cast: ['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan', 'Jamie Lee Curtis'],
    duration: 139,
    language: 'English, Mandarin, Cantonese',
    format: ['4K', 'Dolby Atmos']
  },
  { 
    id: 'f39', 
    title: 'Oldboy', 
    description: 'After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.', 
    release_date: '2003-11-21', 
    poster_url: 'https://picsum.photos/seed/oldboy/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=2HkjwJqdzNg', 
    genre_id: 'g7', 
    genre: mockGenres[6], 
    rating: 8.4,
    director: 'Park Chan-wook',
    cast: ['Choi Min-sik', 'Yoo Ji-tae', 'Kang Hye-jung'],
    duration: 120,
    language: 'Korean',
    format: ['4K', 'Dolby Digital']
  },
  { 
    id: 'f40', 
    title: 'Spider-Man: Into the Spider-Verse', 
    description: 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.', 
    release_date: '2018-12-14', 
    poster_url: 'https://picsum.photos/seed/spiderverse/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=tg52up16eq0', 
    genre_id: 'g1', 
    genre: mockGenres[0], 
    rating: 8.4,
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld', 'Mahershala Ali'],
    duration: 117,
    language: 'English',
    format: ['4K', 'IMAX', 'Dolby Atmos']
  },
  { 
    id: 'f41', 
    title: 'Gone Girl', 
    description: 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.', 
    release_date: '2014-10-03', 
    poster_url: 'https://picsum.photos/seed/gonegirl/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=2-_-1nJf8Vg', 
    genre_id: 'g7', 
    genre: mockGenres[6], 
    rating: 8.1,
    director: 'David Fincher',
    cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris', 'Tyler Perry'],
    duration: 149,
    language: 'English',
    format: ['4K', 'Dolby Digital']
  },
  { 
    id: 'f42', 
    title: 'The Grand Budapest Hotel', 
    description: 'A writer encounters the owner of a declining high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.', 
    release_date: '2014-03-28', 
    poster_url: 'https://picsum.photos/seed/grandbudapest/400/600', 
    trailer_url: 'https://www.youtube.com/watch?v=1Fg5iWmQjwk', 
    genre_id: 'g3', 
    genre: mockGenres[2], 
    rating: 8.1,
    director: 'Wes Anderson',
    cast: ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric', 'Adrien Brody'],
    duration: 99,
    language: 'English',
    format: ['4K', 'Dolby Digital']
  }
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    film_id: 'f1',
    user_id: 'u1',
    content: 'A masterpiece of science fiction. The concept of the Matrix is mind-blowing.',
    rating: 5,
    created_at: '2024-01-01T10:00:00Z',
  },
  {
    id: 'r2',
    film_id: 'f2',
    user_id: 'u2',
    content: 'Inception is a visual treat with a complex but rewarding story.',
    rating: 5,
    created_at: '2024-01-02T11:00:00Z',
  },
  {
    id: 'r3',
    film_id: 'f3',
    user_id: 'u1',
    content: 'The Dark Knight is the best superhero movie ever made. Ledger is incredible.',
    rating: 5,
    created_at: '2024-01-03T12:00:00Z',
  }
];
